### ISSUE TITLE
CSV-import checklist

### ISSUE THREAD

**Issue by crlsocro** [bouvet/bouvet-developer-survey#64]
Now that the csv-import is done, we need to add checks for when updating and deleting the responses

- [x] Add respondad table database like responds to the survey wtih response_id from the csv that are linked to the survey. And have a many-to-many connection to the response-table
- [x] Check for updating values in responses
- [x] Deleting a value
- [x] Adding new fields etc
